cmake_minimum_required(VERSION 3.25)
project(cpp-lab-1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(app src/main.cpp)

install(TARGETS app RUNTIME DESTINATION bin)

if(NOT DEFINED PATCH_VERSION OR PATCH_VERSION STREQUAL "")
  set(PATCH_VERSION 0)
endif()

set(CPACK_PACKAGE_NAME "cpp-lab-1")
set(CPACK_PACKAGE_VERSION "0.0.${PATCH_VERSION}")
set(CPACK_PACKAGE_CONTACT "lotwyx@gmail.com")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "lotwyx")

set(CPACK_GENERATOR "DEB")

include(CPack)
