name: 'C++ CI'

on:
  push:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ${{ matrix.os }}
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        preset: [default, asan, ubsan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      
      - name: Install Ninja (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install ninja

      - name: Configure and build (${{ matrix.preset }})
        run: cmake --workflow --preset ${{ matrix.preset }}

      - name: Run program (${{ matrix.preset }})
        run: ./build/${{ matrix.preset }}/app

      - name: Build .deb package (default only)
        if: matrix.os == 'ubuntu-latest' && matrix.preset == 'default'
        run: cmake --build --preset default --target package

      - name: Create Release
        if: matrix.os == 'ubuntu-latest' && matrix.preset == 'default'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: matrix.os == 'ubuntu-latest' && matrix.preset == 'default'
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/default/cpp-lab-1-0.0.${{ github.run_number }}-Linux.deb
          asset_name: cpp-lab-1-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
